modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="endermanneutral"
version="1.0.0"
displayName="苦力怕中立"
description="使苦力怕成为中立生物，只在被攻击时反击"
authors="DY_XiaoJiaZi"
credits="Thanks to Forge team"
logoFile="icon.png"

[[dependencies.endermanneutral]]
modId="forge"
mandatory=true
versionRange="[47.4.13,)"
ordering="NONE"
side="BOTH"

[[dependencies.endermanneutral]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"